# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-26 18:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0002_auto_20180926_1045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='pasword',
            new_name='password',
        ),
    ]
